### ISSUE TITLE
Component: 'Flavor Suggestions'

### ISSUE THREAD

**Issue by eyeriss42** [larkinds/recurse-randomice#9]
Overview

The user can add suggested flavors. The user can remove the flavor they just added.

Action Items

- [ ]  randomly populate 3 suggested flavors
- [ ] on hover, display flavor name
- [ ] on click, add the suggested flavor to cart

Resources/Instructions

Refer to the [single product page wireframe](https://www.notion.so/Single-Product-2ad8f8c2c7d046be9e7ccf32296b5d46?pvs=4)

**Comment by meru-a** [comment]
@eyeriss42 thanks for clarifying the issue, appreciate the detailed info! But it seems like this issue was already closed and the PR that solved it #22 with scaffolding for the flavor suggestions was already merged to `staging`. 

The added tasks sound like a functionality, especially because the component will have new functions on hover/click and it will be hitting the backend to get 3 flavors. So, I would suggest for us here to create a new issue with these tasks and functionality instead of re-opening the old issue.
